### ISSUE TITLE
Feedback on API

### ISSUE THREAD

**Issue by ronnyroeller** [Collaborne/media-player#47]
A couple of points that I stumbled over, going through the API:
- All API function imply that the library is for video only - yet, it's also supporting audio => should be "media" instead of "video"?
- How about simplifying “videoUrl” field to “url”? It’s obvious that this is the URL for the video (and it might avoid confusions once we support audio files)
- Not clear when to use `onXXX` vs `context.addListener('XXX')` - is it common events via `onXXX`?
- The API contains some very specific functionality (e.g. "Add as cover image") -> Maybe this could be composable, i.e. user can add it to the video-player if required. This might also help with the very long list of properties in the state.
- Using video context is quite complex (taken from announcement post). Could this be simplified by being more declarative, e.g.:
    ```
    <VideoContext ref={contextRef}>
      <VideoPlayer video-url="..." />
    </VideoContext>
    ```
    or power the context via a hook:
    ```
    const contextVar = useVideoContext({ ... }):
    ...
    <VideoContext {...contextVar}>
      <VideoPlayer />
    </VideoContext>
    ```
   (This could significantly ease setting up event listeners because the API would be garantueed to be available on component startup.)

**Comment by bragaru-i** [comment]
Issue completed with refactoring `MediaStore`, adding `<CorePlayer />` + flexibility of the UI Controls elements
